version: "3.3"
services:
  main:
    build:
      context: .
      dockerfile: "docker/main.Dockerfile"
    runtime: "nvidia"
    shm_size: "1g"
    ulimits:
      memlock: -1
      stack: 67108864
    volumes:
      - "~/chess_data:/data"
