EDGE_DETECTION:
  APERTURE: 3
  HIGH_THRESHOLD: 400
  LOW_THRESHOLD: 90
LINE_DETECTION:
  THRESHOLD: 150
LINE_REFINEMENT:
  LINE_THRESHOLD: 3
MAX_OUTLIER_INTERSECTION_POINT_RATIO_PER_LINE: 0.7
RANSAC:
  BEST_SOLUTION_TOLERANCE: 0.1
  OFFSET_TOLERANCE: 0.1
