_BASE_: config://_classifier_base.yaml

DATASET:
  PATH: data://pieces
  BATCH_SIZE: 32
  TRANSFORMS:
    CENTER_CROP: null
    RESIZE: [100, 200]
    RANDOM_HORIZONTAL_FLIP: null

TRAINING:
  PHASES:
    - EPOCHS: 6
      OPTIMIZER:
        LEARNING_RATE: 0.001
        NAME: Adam
      PARAMS: all
