DATASET:
  PATH: data://pieces
  WORKERS: 2
  BATCH_SIZE: 128
  TRANSFORMS:
    CENTER_CROP: [100, 100]
    RESIZE: [100, 100]

TRAINING:
  MODEL: CNN100_3Conv_3Pool_3FC
  PHASES:
    - PARAMS: all
      EPOCHS: 3
      OPTIMIZER:
        NAME: Adam
        LEARNING_RATE: 0.001
