EDGE_DETECTION:
  LOW_THRESHOLD: 90
  HIGH_THRESHOLD: 400
  APERTURE: 3
LINE_DETECTION:
  THRESHOLD: 100
RANSAC:
  OFFSET_TOLERANCE: .15
  BEST_SOLUTION_TOLERANCE: .1
MAX_OUTLIER_INTERSECTION_POINT_RATIO_PER_LINE: .5
LINE_REFINEMENT:
  LINE_THRESHOLD: 3
