_BASE_: config://occupancy_classifier/_base.yaml

RUN:
  DESCRIPTION: 50x50 input size (obtained by downsampling the input image), 2 convolutional layers

DATASET:
  TRANSFORMS:
    CENTER_CROP: [100, 100]
    RESIZE: [50, 50]

TRAINING:
  NETWORK: CNN50
