DATASET:
  SPLIT:
    VAL: .03
    TEST: .1
  PATH: data://occupancy
  WORKERS: 2
  BATCH_SIZE: 128
  TRANSFORMS:
    CENTER_CROP: [100, 100]
    RESIZE: [100, 100]

TRAINING:
  MODEL: CNN100_3Conv_3Pool_2FC
  PHASES:
    - PARAMS: all
      EPOCHS: 2
      OPTIMIZER:
        NAME: Adam
        LEARNING_RATE: 0.001
