DATASET:
  TRANSFORMS:
    CENTER_CROP:
    - 100
    - 100
    RESIZE:
    - 100
    - 100
TRAINING:
  MODEL: ResNet
  PHASES:
  - EPOCHS: 1
    OPTIMIZER:
      LEARNING_RATE: 0.0001
      NAME: Adam
    PARAMS: head
  - EPOCHS: 2
    OPTIMIZER:
      LEARNING_RATE: 1.0e-05
      NAME: Adam
    PARAMS: all
_BASE_: config://occupancy_classifier/_base.yaml
