DATASET:
  TRANSFORMS:
    CENTER_CROP:
    - 50
    - 50
    RESIZE:
    - 100
    - 100
TRAINING:
  MODEL:
    NAME: ResNet
    REGISTRY: OCCUPANCY_CLASSIFIER
  PHASES:
  - EPOCHS: 1
    OPTIMIZER:
      LEARNING_RATE: 0.001
      NAME: Adam
    PARAMS: head
  - EPOCHS: 2
    OPTIMIZER:
      LEARNING_RATE: 0.0001
      NAME: Adam
    PARAMS: all
_BASE_: config://occupancy_classifier/_base.yaml
