name: publish-docs

env:
  GITHUB_ACTOR: georgw777
  GITHUB_REPOSITORY: georgw777/chesscog
  GITHUB_TOKEN: ${{ secrets.CHESSCOG_PAT_TOKEN }}

on:
  push:
    branches: [develop]

jobs:
  build_sphinx_job:
    runs-on: ubuntu-latest
    container: debian:buster-slim

    steps:
      - name: Run build script for Sphinx pages
        env:
          GITHUB_TOKEN: ${{ secrets.CHESSCOG_PAT_TOKEN }}
        run: docs/buildsite.sh
        shell: bash
